import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Profile() {

  const router = useRouter()

  const { profile } = router.query

  // const employee = fetch('/api/user?employeeCode='+profile).then((res) => res.json())

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hey, I'm a profile page! for {profile}
    </>
  )
}
