import Head from 'next/head'
import ProfileView from '@/components/ProfileView'

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY)

export default function Profile({employee}) {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileView details={employee}/>
    </>
  )
}

export async function getServerSideProps(req, res) {

  const { query } = req
  const code = query.profile[0]
  const { data: employee, error } = await supabase.from("employee").select("*").eq("id", code).single()
  return {
    props: {employee},
  }
}
