import Head from 'next/head'
import Image from 'next/image'
import Homepage from '@/components/Homepage'
import Camera from '@/components/utils/Camera'

export default function Home() {
  return (
    <>
      <Head>
        <title>Face In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Camera action={() => {alert("Uhhh")}} />
    </>
  )
}
