import Head from 'next/head'
import Image from 'next/image'
import Dashboard from '@/components/Dashboard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard/>
    </>
  )
}
