import Attendance from '@/components/views/Attendance'
import AttendanceList from '@/components/views/AttendanceList'
import AttendanceReport from '@/components/views/AttendanceReport'
import DownloadData from '@/components/views/DownloadData'
import EditEmployee from '@/components/views/EditEmployee'
import GateAttendance from '@/components/views/GateAttendance'
import NewEntry from '@/components/views/NewEntry'
import UploadData from '@/components/views/UploadData'

import Head from 'next/head'
import { useRouter } from 'next/router'
// import Image from 'next/image'
// import Dashboard from '@/components/Dashboard'

export default function ViewPage() {

  const router = useRouter()
  const { view } = router.query

  const allViews = {
    "attendance": <Attendance/>,
    "new-entry": <NewEntry/>,
    "edit-employee": <EditEmployee/>,
    "attendance-list": <AttendanceList/>,  
    "upload-data": <UploadData/>,
    "download-data": <DownloadData/>,
    "attendance-report": <AttendanceReport/>,
    "gate-attendance": <GateAttendance/>
  }

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Dashboard/> */}
      <main>{allViews[view]}</main>
    </>
  )
}
