import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
// import Image from 'next/image'
// import Dashboard from '@/components/Dashboard'

export default function ViewPage() {

  const router = useRouter()
  const { view } = router.query

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Dashboard/> */}
      <main>{view}</main>
    </>
  )
}
